coordinates:
  name: configstore
  provider: npmjs
  type: npm
revisions:
  0.3.0:
    licensed:
      declared: BSD-2-Clause
  0.3.1:
    licensed:
      declared: BSD-2-Clause
  0.3.2:
    licensed:
      declared: BSD-2-Clause
  1.0.0:
    licensed:
      declared: BSD-2-Clause
