coordinates:
  name: gitconfiglocal
  provider: npmjs
  type: npm
revisions:
  0.0.0:
    licensed:
      declared: BSD-3-Clause
  0.0.1:
    licensed:
      declared: BSD-3-Clause
  0.0.2:
    licensed:
      declared: BSD-3-Clause
  0.0.3:
    licensed:
      declared: BSD-3-Clause
  1.0.0:
    licensed:
      declared: BSD-3-Clause
  2.0.1:
    licensed:
      declared: BSD-3-Clause
