coordinates:
  name: firebase-config
  namespace: com.google.firebase
  provider: mavengoogle
  type: maven
revisions:
  17.0.0:
    licensed:
      declared: OTHER
  22.0.1:
    licensed:
      declared: Apache-2.0
