coordinates:
  name: Microsoft.OpenApi
  provider: nuget
  type: nuget
revisions:
  1.1.1:
    licensed:
      declared: MIT
  1.1.2:
    licensed:
      declared: MIT
  1.1.4:
    licensed:
      declared: MIT
  1.2.2:
    licensed:
      declared: MIT
