coordinates:
  name: Microsoft.Bot.Configuration
  provider: nuget
  type: nuget
revisions:
  4.5.3:
    licensed:
      declared: MIT
  4.6.3:
    licensed:
      declared: MIT
  4.7.0:
    licensed:
      declared: MIT
  4.7.2:
    licensed:
      declared: MIT
  4.8.0:
    licensed:
      declared: MIT
