coordinates:
  name: Microsoft.CrmSdk.XrmTooling.PackageDeployment
  provider: nuget
  type: nuget
revisions:
  9.0.0.4-preview:
    licensed:
      declared: OTHER
  9.1.0.74:
    licensed:
      declared: OTHER
  9.1.0.90:
    licensed:
      declared: OTHER
