coordinates:
  name: Microsoft.Azure.AppConfiguration.AspNetCore
  provider: nuget
  type: nuget
revisions:
  3.0.0:
    licensed:
      declared: OTHER
  3.0.1:
    licensed:
      declared: OTHER
  3.0.2:
    licensed:
      declared: OTHER
  4.0.0-preview:
    licensed:
      declared: OTHER
