coordinates:
  name: prometheus-net
  provider: nuget
  type: nuget
revisions:
  1.2.2.1:
    licensed:
      declared: MIT
  1.3.5:
    licensed:
      declared: MIT
  2.1.0:
    licensed:
      declared: MIT
  2.1.3:
    licensed:
      declared: MIT
  3.1.2:
    licensed:
      declared: MIT
  3.1.4:
    licensed:
      declared: MIT
