coordinates:
  name: System.Configuration.ConfigurationManager
  provider: nuget
  type: nuget
revisions:
  4.4.0:
    licensed:
      declared: MIT
  4.4.1:
    licensed:
      declared: MIT
  4.5.0:
    licensed:
      declared: MIT
  4.5.0-preview1-26216-02:
    licensed:
      declared: MIT
  4.6.0:
    licensed:
      declared: MIT
  4.6.0-preview6.19303.8:
    licensed:
      declared: MIT AND OTHER
  4.6.0-preview8.19405.3:
    licensed:
      declared: MIT
